# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
before_install:
  - Rscript -e 'source("https://bioconductor.org/biocLite.R"); biocLite(c("multtest"));if (!all(c("multtest") %in% installed.packages())) { q(status = 1, save = "no")}'
